theme: minima
title: My first blog
author:
  name             : "Enrico Nicola Armelloni"
  avatar           : 
  bio              : "PhD candidate @ University of Bologna, tenure holder at CNR-IRBIM"
  location         : "Ancona, ITA"
  employer         :
  googlescholar    : "https://scholar.google.com/citations?user=SFFnU7AAAAAJ&hl=it"
  email            : "enrico.armelloni@irbim.cnr.it"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "EnricoNArmelloni"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  orcid            : "http://orcid.org/0000-0002-6679-1912"
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : "earmellowed"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :

description: > # this means to ignore newlines until "baseurl:"
  This is a trial for my personal page. The site is under consttruction
# social links
twitter_username: earmellowed # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
